title: "Docs of Arduino"
description: "..."
theme: jekyll-theme-cayman

# url: "https://gatilhoroxo.github.io"
# baseurl: "/mc-arduino_attempt"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - assets/css

# Customização visual via CSS
markdown: kramdown
kramdown:
  input: GFM
